### ISSUE TITLE
group_by argument for the high-level extract_words function

### ISSUE THREAD

**Issue by ninpnin** [Envinorma/alto#5]
## Use Case

When you work with Alto files, it is often useful to output all words contained in a file. __alto.extract_words__ does this right now. However, a mere list of words loses a lot of structure. Oftentimes what you want is the text inside each ComposedBlock, or on each TextLine.

## Solution

I would most like a **group_by** argument with the options None, "ComposedBlock", and "TextLine". This could be implemented as another function if we want to keep the List[String] codomain of the extract_words function.

**Comment by remidbs** [comment]
Thank you for the suggestion, I implemented it in version 0.0.5
